name: Build and Upload Artifact

on:
  # Trigger workflow when relevant files are modified in a push or pull request
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/maven.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the current working tree
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Setup Java 17 JDK (Adopt)
      - name: Java 17 setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: '17'

      # 3. Setup local Maven package cache to speed up building
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4. Build the project via Maven
      - name: Build via Maven
        run: mvn package -B --file pom.xml

      # 5. Upload the generated JAR as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-plugin
          path: target/*.jar
